CREATE TABLE LANGUAGES (
  ID INT(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE WORDS (
  ID INT(19) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  WORD VARCHAR(2000) NOT NULL,
  LANGUAGE_ID INT(11) NOT NULL REFERENCES LANGUAGES(ID)
);

CREATE TABLE USERS (
  ID INT(19) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(1000) NOT NULL
);

CREATE TABLE TRANSLATIONS(
  SOURCE_ID INT(19) NOT NULL REFERENCES WORDS(ID),
  TRANSLATION_ID INT(19) NOT NULL REFERENCES WORDS(ID)
);

CREATE TABLE USER_WORDS (
  USER_ID INT(19) NOT NULL REFERENCES USERS(ID),
  WORD_ID INT(19) NOT NULL REFERENCES WORDS(ID) # HERE CAN BE USER TRANSLATION CHOICE
);

INSERT INTO LANGUAGES(NAME)
  VALUES ('Russian'), ('English'), ('Spanish'), ('Italian'), ('German');