SET NAMES 'utf8';
SET CHARACTER SET utf8;

CREATE TABLE LANGUAGES (
  ID INT(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE WORDS (
  ID INT(19) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  WORD VARCHAR(2000) NOT NULL,
  LANGUAGE_ID INT(11) NOT NULL REFERENCES LANGUAGES(ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE USERS (
  ID INT(19) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(1000) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE TRANSLATIONS(
  SOURCE_ID INT(19) NOT NULL REFERENCES WORDS(ID),
  TRANSLATION_ID INT(19) NOT NULL REFERENCES WORDS(ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE USER_WORDS (
  USER_ID INT(19) NOT NULL REFERENCES USERS(ID),
  WORD_ID INT(19) NOT NULL REFERENCES WORDS(ID) # HERE CAN BE USER TRANSLATION CHOICE
) DEFAULT CHARSET=utf8;

INSERT INTO LANGUAGES(NAME)
  VALUES ('Russian'), ('English'), ('Spanish'), ('Italian'), ('German');